language: node_js
node_js: '12'

os:
  - linux
  - osx

script:
  - npm run lint
  - npm run check
  - npm run build
  - npm run bundle:$TRAVIS_OS_NAME

after_success:
  # Upload test coverage to codecov.io
  - bash <(curl -s https://codecov.io/bash) -F $TRAVIS_OS_NAME

deploy:
  # Do a semantic release (only on Linux to avoid duplication)
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux

  # Deploy build artifacts to Github release
  # page on *any* tag (including those generated for a semantic release)
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: bin/*.tar.gz
    skip_cleanup: true
    on:
      tags: true
